# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "manejo-inventario-ashley"
client_id = "04664990a1d1d52fbdc089346929012a"
application_url = "https://facilities-newark-immune-catalog.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://facilities-newark-immune-catalog.trycloudflare.com/auth/callback",
  "https://facilities-newark-immune-catalog.trycloudflare.com/auth/shopify/callback",
  "https://facilities-newark-immune-catalog.trycloudflare.com/api/auth/callback",
  "https://facilities-newark-immune-catalog.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "issaworkshop.myshopify.com"
